name: "🚀 Feature Request / Improvement"
description: "새로운 기능 추가 또는 기존 기능 개선 요청"
title: "[Feat] "
labels: ["✨ feat", "🛠 enhancement"]
assignees: []

body:
  - type: textarea
    id: what-why
    attributes:
      label: 📌 설명 (What & Why)
      description: 어떤 기능을 추가하거나 개선하려는지, 그 배경이나 목적을 작성해주세요.
      placeholder: |
        예) 마이페이지에 ‘최근 활동 내역’을 추가합니다.
        사용자 관점에서 어떤 행동을 했는지 되돌아볼 수 있도록 하여 리텐션을 높이고자 합니다.

  - type: textarea
    id: todo
    attributes:
      label: ✅ 작업 내용 (Todo)
      description: 기능을 구현하기 위해 수행해야 할 주요 작업 항목을 작성해주세요.
      value: |
        - [ ] 기획 확인 및 기초 UI 구성
        - [ ] API 설계 및 컨트롤러 생성
        - [ ] DB 테이블/엔티티 수정
        - [ ] 프론트 연동 테스트
        - [ ] QA 및 문서화

  - type: textarea
    id: expected-result
    attributes:
      label: 🔎 예상 결과 / 기대 효과
      description: 기능이 완료되었을 때 사용자 또는 시스템 측면에서 어떤 변화가 있는지 작성해주세요.
      placeholder: |
        예) 사용자는 마이페이지에서 본인의 최근 활동 내역을
