name: '🎨 FE Feature Request'
description: '프론트엔드 기능 개발 또는 개선 요청'
title: '[Feat] '
labels: ['✨ frontend', '🎨 UI/UX']
assignees: []

body:
  - type: textarea
    id: what-why
    attributes:
      label: 📌 설명 (What & Why)
      description: 어떤 기능을 구현하려는지, 그 배경이나 목적을 설명해주세요.
      placeholder: |
        예) 회원가입 페이지에 아이디 중복 확인 기능을 추가합니다.
        사용자가 가입 단계에서 미리 아이디 사용 가능 여부를 확인하여, 불필요한 오류를 방지하고자 합니다.

  - type: textarea
    id: design-reference
    attributes:
      label: 🖼️ 디자인 및 기획 참고
      description: 관련된 피그마 링크, 디자인 에셋, 기획 문서를 첨부해주세요.
      placeholder: |
        - 피그마 링크: [https://www.figma.com/...]
        - 기획 문서: [노션 페이지 링크]

  - type: textarea
    id: todo
    attributes:
      label: ✅ 주요 작업 목록 (Todo)
      description: 기능을 구현하기 위해 수행할 작업들을 체크리스트로 작성해주세요.
      value: |
        - [ ] API 명세 확인 및 연동
        - [ ] UI/UX 컴포넌트 개발
        - [ ] 상태 관리 로직 구현
        - [ ] 유효성 검사 로직 추가
        - [ ] 테스트 및 QA

  - type: textarea
    id: expected-result
    attributes:
      label: 🔎 예상 결과
      description: 기능이 완료되었을 때 화면에 나타날 예상 결과나 사용자가 경험할 변화를 설명해주세요.
      placeholder: |
        예) 사용자가 아이디 입력 후 '중복 확인' 버튼을 누르면
        성공/실패 메시지 팝업이 나타납니다.
